apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controldb-data
  namespace: controldb
  labels:
    app.kubernetes.io/name: controldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard
